### ISSUE TITLE
Error when apostrophe is in the path

### ISSUE THREAD

**Issue by puerile22** [wrangr/awis#3]
When I tried to query the path: Top/Shopping/Clothing/Children's, it gave me an error: 
`error: err Error: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`

**Comment by lupomontero** [comment]
Many thanks for the feedback @puerile22!

I've had a quick look and I can easily replicate the issue... so definitely a problem. I'll add a test case for this and look at it in more detail shortly.

**Comment by lupomontero** [comment]
Just released a new version including the fix (0.0.9)

Can you update and see if this fixes the problem for you?

**Comment by puerile22** [comment]
Thanks it fixes the problem! Thank you for your quick update!
