### ISSUE TITLE
RankByCountry is missing country codes

### ISSUE THREAD

**Issue by Janpot** [wrangr/awis#5]
the API returns:

```
{
  "trafficData": {
    "dataUrl": "google.com/",
    "rankByCountry": {
      "country": [
        {
          "rank": "6",
          "contribution": {
            "pageViews": "0.5%",
            "users": "0.5%"
          }
        },
        {
          "rank": "2",
          "contribution": {
            "pageViews": "13.0%",
            "users": "9.1%"
          }
        },
        ...
```

These results are missing country code information.

**Comment by lupomontero** [comment]
Many thanks for the PR! I just merged it and will be publishing a new version to npm in the next few minutes... ;-)

**Comment by Janpot** [comment]
Hi @lupomontero 

Thanks for the quick response, really appreciate it. I have a few comments left:

https://github.com/wrangr/awis/pull/4 can probably closed now.

I also saw the code does a few things that `xml2js` already provides out of the box:

1. you can flatten the arrays automatically with `explicitArray` option.
2. you can lowercase names with the `tagNameProcessors` and `attrNameProcessors`. You can also use this to remove the namespace prefixes. There are standard `firstCharLowerCase` and `stripPrefix` processors provided.

**Comment by lupomontero** [comment]
Hi @Janpot,

Thanks for all the help ;-)

I'm kinda busy with other stuff at the moment, can you open new issue and/or send a PR with the suggested changes?

Cheers,

L
